### ISSUE TITLE
Fiware-pep-proxy Dockerfile

### ISSUE THREAD

**Issue by albertinisg** [ging/fiware-pep-proxy#10]
Hi!

As I did in `fiware-idm`, I'm just pointing that we've also created an image for `fiware-pep-proxy` :P 

We've created the `fiware-pep-proxy` image based in the [Node official image](https://hub.docker.com/_/node/).

Like the `fiware-idm` one, it's been made mainly for integration so, it requires the following:
* docker-compose (for components integration)
* A `fiware-idm` instance 
* An `Authzforce` instance
* An app to protect (we've been using Orion)

We've created a template `config.js` with values by default. With docker-compose, this variables can be modified just by passing the values in the docker-compose `yml` file like:
```
pepwilma:
    image: bitergia/pep-wilma:4.3.0
    links:
        - orion
        - idm
        - authzforce
    volumes_from:
        - idm
    environment:
        - AUTHZFORCE_HOSTNAME=authzforce
        - AUTHZFORCE_PORT=8080
        - IDM_KEYSTONE_HOSTNAME=idm
        - IDM_KEYSTONE_PORT=5000
        - APP_HOSTNAME=orion
        - APP_PORT=10026
        - PEP_USERNAME=pepproxy@test.com
        - PEP_PASSWORD=test
        - PEP_PORT=1026
        - IDM_USERNAME=user0@test.com
        - IDM_USERPASS=test
        - MAGIC_KEY=daf26216c5434a0a80f392ed9165b3b4
```
Finally, and just to make things a bit easier, we've added a really simple script based on the 'Resource Owner Password Credentials Grant', to get a fresh Oauth2 token just by launching a command:
```
docker exec -i -t <pepwilma-container-name> auth-token.sh <user-email> <password>
```

All the information regarding the `fiware-pep-proxy` image is available [here](https://github.com/Bitergia/fiware-chanchan-docker/tree/master/images/pep-wilma)

Again, feel free to use it as you need.

Best!
