### ISSUE TITLE
Dockerized PEP Proxy won't connect to Authzforce

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-pep-proxy#62]
If you set up a PEP proxy  to use AuthZforce using `docker-compose` as shown:

```yml
 pep-proxy:
    image: fiware/pep-proxy
    depends_on:
      - keyrock
      - authzforce
    ports:
      - "1027:1027"
    expose:
      - "1027"
    environment:
      - PEP_PROXY_APP_HOST=orion
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_PORT=1027
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=xxxxxxxxx
      - PEP_PROXY_USERNAME=yyyyyyy
      - PEP_PASSWORD=zzzzzzz
      - PEP_PROXY_PDP=authzforce
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_AZF_PROTOCOL=http
      - PEP_PROXY_AZF_HOST=authzforce
      - PEP_PROXY_AZF_PORT=8080
```

Level 2 - Basic Authorization from **Keyrock**  is used rather than Level 3 - Advanced Authorization from **Authzforce** - the  ` PEP_PROXY_AUTH_ENABLED` is incorrectly read as a string rather than a boolean
